# coding=utf-8
# The MIT License (MIT)
# Copyright (c) 2016 mateor

python_library(
  name = 'lists',
  sources = globs('*.py'),
  dependencies = [
    'src/python/betarepo/datastructures/linear/abstract',
  ]
)
