# coding=utf-8
# The MIT License (MIT)
# Copyright (c) 2016 mateor

python_library(
  name = 'sorting',
  sources = globs('*.py'),
  dependencies = [
    'src/python/betarepo/datastructures/trees/concrete/heaps',
    'src/python/betarepo/datastructures:comparison_mixin',
  ],
)
