# coding=utf-8
# The MIT License (MIT)
# Copyright (c) 2016 mateor

python_tests(
  name = 'lists',
  sources = globs('*.py'),
  dependencies = [
    'src/python/betarepo/datastructures/linear/abstract',
    'src/python/betarepo/datastructures/linear/concrete/lists',
  ],
)
