# coding=utf-8
# The MIT License (MIT)
# Copyright (c) 2016 mateor

# TODO(mateo): Ban source dependencies in abstract classes? Would need graph rules.
python_library(
  name = 'stacks',
  sources = globs('*.py'),
  dependencies = [
    'src/python/betarepo/datastructures/linear/abstract',
  ],
)
