# coding=utf-8
# The MIT License (MIT)
# Copyright (c) 2016 mateor

python_library(
  name = 'heaps',
  sources = globs('*.py'),
  dependencies = [
    'src/python/betarepo/datastructures:comparison_mixin',
  ],
)

python_binary(
  name='run',
  source='array_heap.py',
  dependencies = [
    'src/python/betarepo/datastructures:comparison_mixin',
  ]
)