# coding=utf-8
# The MIT License (MIT)
# Copyright (c) 2016 mateor

# TODO(mateo): Ban source dependencies in abstract classes? Would need graph rules.
python_library(
  name = 'abstract',
  sources = globs('*.py'),
)
