# coding=utf-8
# The MIT License (MIT)
# Copyright (c) 2016 mateor

python_tests(
  name = 'test_comparison_mixin',
  sources = [
    'test_comparison_mixin.py'
  ],
  dependencies = [
    'src/python/betarepo/algorithms/sorting',
  ],
)