# coding=utf-8
# The MIT License (MIT)
# Copyright (c) 2016 mateor

python_tests(
  name = 'queues',
  sources = globs('*.py'),
  dependencies = [
    'src/python/betarepo/datastructures/linear/concrete/queues',
  ]
)
